#!/bin/bash
set -ex
echo 'Reconfiguring openssh-server' >> /dev/kmsg
echo 'Collecting entropy ...' >> /dev/kmsg

# drain entropy pool to get rid of stored entropy after boot.
dd if=/dev/urandom of=/dev/null bs=1024 count=10 2>/dev/null

while entropy=$(cat /proc/sys/kernel/random/entropy_avail); [ "$entropy" -lt 100 ]
  do sleep 1
done

rm -f /etc/ssh/ssh_host_*
echo 'Generating new SSH host keys ...' >> /dev/kmsg
dpkg-reconfigure openssh-server
echo 'Reconfigured openssh-server' >> /dev/kmsg
