version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Run Shellcheck
          command: |
            make shellcheck

      - run:
          name: Create Raspbian ARM 32bit
          command: |
            HYPRIOT_OS_VERSION=${CIRCLE_TAG} make armhf-raspbian
          no_output_timeout: 1800

      - run:
          name: Create Debian ARM 32bit
          command: |
            HYPRIOT_OS_VERSION=${CIRCLE_TAG} make armhf-debian
          no_output_timeout: 1800

      - run:
          name: Create Debian ARM 64bit
          command: |
            HYPRIOT_OS_VERSION=${CIRCLE_TAG} make arm64-debian
          no_output_timeout: 1800

      - run:
          name: Prepare artifacts
          command: |
            mkdir -p output
            cp rootfs* output/

      - store_artifacts:
          path: /home/circleci/project/output

      - deploy:
          name: Deploy
          command: |
            if [ "$CIRCLE_TAG" != "" ]; then
              curl -sSL https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip -o ghr.zip
              unzip ghr.zip
              if [[ $CIRCLE_TAG = *"rc"* ]]; then
                pre=-prerelease
              fi
              ./ghr $pre -u hypriot $CIRCLE_TAG output/
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
